apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-k8s-leet-go-backend
  labels:
    component: backend
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-leet-go.name" . }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-leet-go.name" . }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: "ksa-k8s-leet-go-backend"
      initContainers:
        - name: init-backend
          image: busybox:1.28
          command: ['sh', '-c', 'sleep 60']
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: service-app
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: service-app
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: service-app
          env:
            - name: PGPASSWORD
              value: "{{ .Values.postgresql.auth.password }}"

            - name: DB_HOST
              value: "{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
            - name: DB_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: DB_NAME
              value: "{{ .Values.postgresql.auth.database }}"
            - name: DB_PORT
              value: "{{ .Values.postgresql.containerPorts.postgresql }}"
            
            - name: JWT_PRIVATE_KEY
              value: "{{ .Values.backend.jwt_private_key }}"
            - name: TOKEN_TTL
              value: "{{ .Values.backend.token_ttl }}"

            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis-cluster.{{ .Release.Namespace }}.svc.cluster.local"
            - name: REDIS_PORT
              value: "{{ index .Values "redis-cluster" "cluster" "externalAccess" "service" "port" }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis-cluster
                  key: redis-password
                  optional: false
          
          resources: {}
