apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-leet-go.name" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: service-app
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "k8s-leet-go.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}